# Generated by Django 3.0.5 on 2020-04-08 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0002_position'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('logo', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('description_html', models.TextField()),
                ('keywords', models.TextField()),
                ('url', models.URLField(default='')),
                ('resume', models.FileField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='positions.Position')),
            ],
        ),
    ]
