# Generated by Django 3.0.4 on 2020-03-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='descriptionHtml',
            new_name='description_html',
        ),
    ]
