# Generated by Django 3.0.4 on 2020-03-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200317_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
