# Generated by Django 3.0.5 on 2020-04-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resume_text',
            field=models.TextField(default=''),
        ),
    ]
