# Generated by Django 3.0.5 on 2020-04-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_description_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
