# Generated by Django 3.0.4 on 2020-03-26 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='jobs.Position'),
            preserve_default=False,
        ),
    ]
