# Generated by Django 3.0.5 on 2020-04-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resume_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
