# Generated by Django 3.0.4 on 2020-03-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.Position'),
        ),
    ]
