# Generated by Django 3.0.4 on 2020-03-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200326_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
