# Generated by Django 3.0.4 on 2020-04-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
